services:
  - type: web
    name: plankton
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn run:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PLANTID_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///plankton.db
      - key: PYTHON_VERSION
        value: 3.11.0
